name: "auto-assign"
description: "Automatically assign team for review"
inputs:
  TEAM:
    required: true
    description: "Team name"
    default: developers
  GITHUB_TOKEN:
    required: true
    description: "Your github token"
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
